version: '3.7'
services:
    mbdb:
        image: postgres:11
        hostname: mbdb
        environment:
            - POSTGRES_PASSWORD=${PGPASSWORD}
    bot:
        build: .
        depends_on:
            - mbdb
        environment:
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
            - GOOGLE_API_KEY=${GOOGLE_API_KEY}
            - S3_BUCKET=${S3_BUCKET}
            - PGPASSWORD=${PGPASSWORD}
            - PGHOST=${PGHOST}
            - PGPORT=${PGPORT}
            - PGUSER=${PGUSER}
            - PGNAME=${PGNAME}
            - PYTHONUNBUFFERED=1
            - OWNER=${OWNER:-203285581004931072}
            - DEVELOPERS=${DEVELOPERS:-766337842031886336}
            - DEV_GUILDS=${DEV_GUILDS:-None}
            - STAGING_PREFIX=${STAGING_PREFIX:-None}
            - SURPRESS_PICTURE_ADDER=${SURPRESS_PICTURE_ADDER:-0}
        healthcheck:
            test: ["CMD-SHELL", "discordhealthcheck"]
