version: '3.7'
services:
    mbdb:
        image: postgres:11
        hostname: mbdb
        environment:
            - POSTGRES_PASSWORD=${PGPASSWORD}
    bot:
        build: .
        depends_on:
            - mbdb
        environment:
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
            - GOOGLE_API_KEY=${GOOGLE_API_KEY}
            - S3_BUCKET=${S3_BUCKET}
            - PGPASSWORD=${PGPASSWORD}
            - PGHOST=${PGHOST}
            - PGPORT=${PGPORT}
            - PGUSER=${PGUSER}
            - PGNAME=${PGNAME}
            - PYTHONUNBUFFERED=1
