#!/usr/bin/env bash

set -Eeuo pipefail

if [[ -z $DISCORD_BOT_TOKEN ]]; then
  echo >&2 "Provide DISCORD_BOT_TOKEN"
  exit 1
fi

export PGPASSWORD="${PGPASSWORD:-testpassword}"
export PGHOST="${PGHOST:-mbdb}"
export PGPORT="${PGPORT:-5432}"
export PGUSER="${PGUSER:-postgres}"
export PGNAME="${PGNAME:-postgres}"

docker-compose down

docker-compose up --build --abort-on-container-exit --remove-orphans
