#!/usr/bin/env bash

repo_dir=${REPO_DIR:-/makubot}

while [ ! -d "$repo_dir/src" ]; do
    echo "Waiting for $repo_dir/src to come up..."
    sleep 1
done

cd "$repo_dir" || (echo >&2 "Couldn't CD into $repo_dir" && exit 1)
python3.8 -m src
